### ISSUE TITLE
Clear method

### ISSUE THREAD

**Issue by vadixidav** [axiomhq/rust-cuckoofilter#33]
I would like it if the CuckooFilter had a `.clear()` method which deleted all the entries. This would be useful to me when doing kNN graph search (HNSW) to prevent reallocating memory on each nearest neighbor search. This can be a problem when dealing with small search spaces since a lot of the time can be taken up on just allocation since little searching actually needs to be done.

Is this of interest? I assume it should be a small change. Just looking to see if this kind of change would be accepted.

**Comment by seiflotfy** [comment]
+1 interested in creating a PR
