### ISSUE TITLE
Move to Rust 2018 edition

### ISSUE THREAD

**Issue by LovecraftianHorror** [axiomhq/rust-cuckoofilter#43]
There were a number of changes from the Rust 2018 edition, so to keep this crate up to date with current Rust it would be nice to update to edition 2018. More info on the topic is listed [here](https://doc.rust-lang.org/edition-guide/editions/index.html).

Again I would be open to submitting a PR for this change.

**Comment by seiflotfy** [comment]
I'd highly appreciate that 👍

**Comment by JayKickliter** [comment]
This can be closed due to #47
