### ISSUE TITLE
Remove dev feature flag

### ISSUE THREAD

**Issue by LovecraftianHorror** [axiomhq/rust-cuckoofilter#50]
It's no longer recommended to install `clippy` through crates.io ([deprecation notice on the landing page](https://lib.rs/crates/clippy)). Since there will likely already be a breaking change from #48 it might be a good time to remove the `dev` feature flag as well.

**Comment by JayKickliter** [comment]
+1

The `dev` feature caused build errors for me locally when running `cargo test --all-features` on #48

**Comment by LovecraftianHorror** [comment]
#51 closes this
